### ISSUE TITLE
Testing a issue

### ISSUE THREAD

**Issue by machanth** [machanth/DTAOpenhack#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

#6 
> Thanks! We'll be in touch soon.

**Comment by gastori** [comment]
Done
